set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WEB.WEBVIEW2 "$ENV{NUGET}/Microsoft.Web.WebView2")

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WINDOWS.CPPWINRT "$ENV{NUGET}/Microsoft.Windows.CppWinRT")

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WINDOWS.IMPLEMENTATIONLIBRARY
    "$ENV{NUGET}/Microsoft.Windows.ImplementationLibrary"
    )
