set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WEB.WEBVIEW2
    "$ENV{LIBS}/Nuget/Microsoft.Web.WebView2.1.0.2739.15"
    )

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WINDOWS.CPPWINRT
    "$ENV{LIBS}/Nuget/Microsoft.Windows.CppWinRT.2.0.240405.15"
    )

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WINDOWS.IMPLEMENTATIONLIBRARY
    "$ENV{Libs}/Nuget/Microsoft.Windows.ImplementationLibrary.1.0.240803.1"
    )
