set(FETCHCONTENT_SOURCE_DIR_ADA-URL.ADA "$ENV{LIBS}/ada-url/ada/singleheader")

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WEB.WEBVIEW2 "$ENV{LIBS}/Nuget/Microsoft.Web.WebView2")

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WINDOWS.CPPWINRT
    "$ENV{LIBS}/Nuget/Microsoft.Windows.CppWinRT"
    )

set(FETCHCONTENT_SOURCE_DIR_MICROSOFT.WINDOWS.IMPLEMENTATIONLIBRARY
    "$ENV{LIBS}/Nuget/Microsoft.Windows.ImplementationLibrary"
    )
