name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        id: deps
        with:
          path: |
            build/_deps
          key: deps-${{ hashFiles('CMakeLists.txt') }}

      - name: CMake
        run: |
          Import-Module ${{ github.workspace }}\Tools\PowerShell
          Invoke-CMake

      # - name: Stable Release
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     Import-Module ${{ github.workspace }}\Tools\PowerShell
      #     Invoke-StableRelease

      # - name: Nightly Release
      #   if: github.ref == 'refs/heads/next'
      #   run: |
      #     Import-Module ${{ github.workspace }}\Tools\PowerShell
      #     Invoke-NextRelease
