name: Glow

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Glow
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          path: glow

      - name: Checkout mthierman.pages.dev
        uses: actions/checkout@v4
        with:
          repository: mthierman/mthierman.com
          token: ${{ secrets.WEBSITE }}
          path: mthierman.com

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/glow/build/_deps
          key: deps-${{ hashFiles('glow/cmake/deps.cmake') }}

      - name: CMake
        run: |
          Set-Location ${{ github.workspace }}\glow
          Import-Module ${{ github.workspace }}\glow\tools\PowerShell
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vspath = & $vswhere -products * -latest -property installationPath
          & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -Arch $Arch -HostArch $HostArch -SkipAutomaticLocation
          cmake --preset "Ninja MSVC"
          cmake --build --preset "Ninja MSVC Release"
          .\scripts\manifest.ps1
          .\scripts\compress.ps1
          .\scripts\publish.ps1

      - name: Update website
        run: |
          Set-Location ${{ github.workspace }}\mthierman.com
          Copy-Item "${{ github.workspace }}\glow\build\manifest.json" -Destination "${{ github.workspace }}\mthierman.com\src\content\projects\glow.json"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Update Glow'
          git push
