name: Glow

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
          path: glow

      - name: Checkout website
        uses: actions/checkout@v4
        with:
          repository: mthierman/mthierman.com
          token: ${{ secrets.WEBSITE }}
          path: mthierman.com

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: glow/pnpm-lock.yaml

      - name: Install node_modules
        run: |
          Set-Location ${{ github.workspace }}\glow
          pnpm install
          pnpm manifest

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/glow/build/_deps
          key: deps-${{ hashFiles('glow/CMakeLists.txt') }}

      - name: CMake
        run: |
          Set-Location ${{ github.workspace }}\glow
          Import-Module ${{ github.workspace }}\glow\tools\PowerShell
          Invoke-DevShell
          Invoke-CMake
          Compress-Glow
          Publish-Glow

      - name: CTest
        run: |
          Set-Location ${{ github.workspace }}\glow
          Import-Module ${{ github.workspace }}\glow\tools\PowerShell
          Invoke-CTest

      - name: Update website
        run: |
          Set-Location ${{ github.workspace }}\mthierman.com
          Copy-Item "${{ github.workspace }}\glow\build\manifest.json" -Destination "${{ github.workspace }}\mthierman.com\src\content\projects\glow.json"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Update Glow'
          git push
