name: Glow

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            build/_deps
          key: deps-${{ hashFiles('CMakeLists.txt') }}

      - name: CMake
        run: |
          Import-Module ${{ github.workspace }}\tools\PowerShell
          Invoke-DevShell
          Invoke-CMake
