name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Make release & update website
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup
        uses: mthierman/github-actions/setup@main
        with:
          path: "Glow"

      - name: Website
        uses: mthierman/github-actions/website@main
        with:
          token: ${{ secrets.WEBSITE }}

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/Glow/build/_deps
          key: deps-${{ hashFiles('Glow/cmake/deps.cmake') }}

      - name: CMake
        run: |
          .\powershell-scripts\dev.ps1
          Set-Location ${{ github.workspace }}\Glow
          cmake --preset "Ninja MSVC"
          cmake --build --preset "Ninja MSVC Release"

      - name: Generate manifest
        run: .\scripts\manifest.ps1

      - name: Compress build
        run: .\scripts\compress.ps1

      - name: Publish build
        run: .\scripts\publish.ps1

      - name: Update website
        run: |
          Set-Location ${{ github.workspace }}\mthierman.com
          Copy-Item "${{ github.workspace }}\Glow\build\manifest.json" -Destination "${{ github.workspace }}\mthierman.com\src\content\projects\glow.json"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Update Glow'
          git push
