name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
      - name: Cache
        uses: actions/cache@v3
        id: deps
        with:
          path: |
            build/_deps
          key: deps-${{ hashFiles('cmake/PackageInfo.cmake') }}
      # - name: Compress
      #   run: |
      #     Import-Module ${{ github.workspace }}/tools/scripts/pwsh
      #     Export-ReleaseNotes
      #     $commit = Get-Commit
      #     Compress-Repo
      #     $archive = Get-Archive
      #     $notes = Get-ReleaseNotes

      #     if ("${{ github.ref_name }}" -eq "main") {
      #       gh release delete $commit -y
      #       gh release create $commit $archive -F $notes -t "Glow $version"
      #     }
      - name: Compress
        run: |
          Import-Module ${{ github.workspace }}/tools/scripts/pwsh
          Export-ReleaseNotes
          $commit = Get-Commit
          $commit
      # - name: CMake
      #   run: |
      #     Import-Module ${{ github.workspace }}/tools/scripts/pwsh
      #     Enter-DevShell64 && Build-CMake
