name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        id: deps
        with:
          path: |
            build/_deps
          key: deps-${{ hashFiles('cmake/PackageInfo.cmake') }}

      - name: CMake
        run: |
          Import-Module ${{ github.workspace }}/tools/pwsh
          Enter-DevShell64 && Build-CMake

      - name: Release
        run: |
          Import-Module ${{ github.workspace }}/tools/pwsh
          Export-Notes
          Compress-Repo
          $name = Get-Name
          $version = Get-Version
          $archive = Get-Archive
          $notes = Get-Notes

          if ("${{ github.ref_name }}" -eq "main") {
            gh release delete $version -y
            gh release create $version $archive -F $notes -t "$name $version"
          }
