name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true

      - name: Cache
        uses: actions/cache@v3
        id: deps
        with:
          path: |
            build/_deps
          key: deps-${{ hashFiles('cmake/PackageInfo.cmake') }}

      - name: CMake
        run: |
          Import-Module ${{ github.workspace }}/tools/pwsh
          Invoke-CMake

      - name: Release
        if: ${{ github.ref_name }}" -eq "main"
        run: |
          Import-Module ${{ github.workspace }}/tools/pwsh
          Invoke-Release
