name: Test

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
      - name: Test
        run: |
          Import-Module ${{ github.workspace }}/tools/scripts/pwsh
